name: Cloud Challenge - Hello World

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Execute the Python script
      - name: Run hello-world.py
        run: python hello-world.py

      # Step 4: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      # Step 5: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 6: Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Step 7: Validate Terraform
      - name: Validate Terraform
        run: terraform validate

      # Step 8: Plan Terraform
      - name: Plan Terraform
        run: terraform plan -out=tfplan

      # Step 9: Apply Terraform
      - name: Apply Terraform
        run: terraform apply -auto-approve tfplan

